/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:7aa4f0bc-ec3a-4239-a36c-3fe928f1b889",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_6cKb8yCPA",
    "aws_user_pools_web_client_id": "5q3dvu610ba98tkl90uvntmen7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://x5k57sbyybgohduactop7thhem.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456"
};


export default awsmobile;
